Truncate table Health_Facility_Location
SELECT TOP [LICENSED_CERTIFIED]
      ,[FLAG]
      ,[T18_19]
      ,[FACID]
      ,[FAC_STATUS_TYPE_CODE]
      ,[ASPEN_FACID]
      ,[CCN]
      ,[TERMINAT_SW]
      ,[PARTICIPATION_DATE]
      ,[APPROVAL_DATE]
      ,[NPI]
      ,[CAN_BE_DEEMED_FAC_TYPE]
      ,[CAN_BE_CERTIFIED_FAC_TYPE]
      ,[DEEMED]
      ,[AO_CD]
      ,[DMG_EFCTV_DT]
      ,[AO_TRMNTN_DT]
      ,[AO_NAME]
      ,[FACNAME]
      ,[FAC_TYPE_CODE]
      ,[FAC_FDR]
      ,[LTC]
      ,[CAPACITY]
      ,[ADDRESS]
      ,[CITY]
      ,[ZIP]
      ,[ZIP9]
      ,[FACADMIN]
      ,[CONTACT_EMAIL]
      ,[CONTACT_FAX]
      ,[CONTACT_PHONE_NUMBER]
      ,[COUNTY_CODE]
      ,[COUNTY_NAME]
      ,[DISTRICT_NUMBER]
      ,[DISTRICT_NAME]
      ,[ISFACMAIN]
      ,[PARENT_FACID]
      ,[FAC_FAC_RELATIONSHIP_TYPE_CODE]
      ,[START_DATE]
      ,[LICENSE_NUMBER]
      ,[BUSINESS_NAME]
      ,[LICENSE_STATUS_DESCRIPTION]
      ,[INITIAL_LICENSE_DATE]
      ,[LICENSE_EFFECTIVE_DATE]
      ,[LICENSE_EXPIRATION_DATE]
      ,[ENTITY_TYPE_DESCRIPTION]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[LOCATION]
      ,[HCAI_ID]
      ,[CCLHO_CODE]
      ,[CCLHO_NAME]
      ,[FIPS_COUNTY_CODE]
      ,[BIRTHING_FACILITY_FLAG]
      ,[TRAUMA_PED_CTR]
      ,[TRAUMA_CTR]
      ,[TYPE_OF_CARE]
      ,[CRITICAL_ACCESS_HOSPITAL]
      ,[DATA_DATE]
      ,[DMG_EFCTV_DATE]
  FROM [Dev].[dbo].[Health_Facility_Location]

  Select *
  From Health_Facility_Location


  ---questions and solutions

---to ulter the data type of the column

alter table Health_Facility_Location
alter column CAPACITY int null



--CONFIRM DATA LOADED INTO DATABASE
SELECT *
FROM Health_Facility_Location

--TOTAL COUNT OF FACILITIES IN CALIFORNIA
SELECT 
COUNT (FACID) AS TOTAL_COUNT_OF_REGISTERED_FACILITIES_IN_CALIFORNIA
FROM Health_Facility_Location

--SAVE AS VIEW
CREATE VIEW VW_TOTAL_COUNT_OF_REGISTERED_FACILITIES_IN_CALIFORNIA AS
(
SELECT 
COUNT (FACID) AS TOTAL_COUNT_OF_REGISTERED_FACILITIES_IN_CALIFORNIA
FROM Health_Facility_Location
)

--TOTAL COUNTS OF FACILITIES BY FACILITY TYPE
SELECT FAC_TYPE_CODE,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_TYPE
FROM Health_Facility_Location
GROUP BY FAC_TYPE_CODE
--ORDER BY TOTAL_NUMBER_OF_FACILITIES DESC

--SAVE AS VIEW
CREATE VIEW VW_TotalNumberOfFacilitiesByType AS
SELECT FAC_TYPE_CODE,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_TYPE
FROM Health_Facility_Location
GROUP BY FAC_TYPE_CODE
--ORDER BY TOTAL_NUMBER_OF_FACILITIES DESC



--NUMBER OF BEDS
SELECT 
SUM(CAPACITY) AS NUMBER_OF_BEDS
FROM Health_Facility_Location

--SAVE AS VIEW

select *
from VwNunmbersOfBeds
drop view if exists  VwNunmbersOfBeds

CREATE VIEW VwNunmbersOfBeds AS
SELECT 
SUM(CAPACITY) AS NUMBER_OF_BEDS
FROM Health_Facility_Location




--NUMBER OF FACILITY TYPE
SELECT 
COUNT(DISTINCT FAC_TYPE_CODE) AS NUMBER_OF_FACILITY_TYPE
FROM Health_Facility_Location


--SAVE AS VIEW
CREATE VIEW VW_NUMBER_OF_FACILITY_TYPE AS
(
SELECT 
COUNT(DISTINCT FAC_TYPE_CODE) AS NUMBER_OF_FACILITY_TYPE
FROM Health_Facility_Location
)


--TOTAL NUMBER OF FACILITIES IN EACH COUNTY
SELECT COUNTY_NAME,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY
FROM Health_Facility_Location
GROUP BY COUNTY_NAME
ORDER BY TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY DESC

--SAVE AS VIEW
CREATE VIEW VW_TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY AS
(
SELECT COUNTY_NAME,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY
FROM Health_Facility_Location
GROUP BY COUNTY_NAME
--ORDER BY TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY DESC
)

--Available hospice care beds
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS NUMBER_OF_HOSPICE_BEDS
FROM Health_Facility_Location
WHERE FAC_TYPE_CODE='HOSPICE'
GROUP BY FAC_TYPE_CODE

--SAVE AS VIEW
CREATE VIEW VW_HOSPICE_BEDS AS
(
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS NUMBER_OF_HOSPICE_BEDS
FROM Health_Facility_Location
WHERE FAC_TYPE_CODE='HOSPICE'
GROUP BY FAC_TYPE_CODE
)

select *
from VW_HOSPICE_BEDS

-- COUNT OF ACUTE BEDS BY FACILITY TYPE
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS_BY_FAC_TYPE
FROM Health_Facility_Location
WHERE FACNAME LIKE '%ACUTE%'
GROUP BY FAC_TYPE_CODE

--SAVE AS VIEW
CREATE VIEW VW_ACUTE_BEDS_BY_FAC_TYPE AS
(
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS_BY_FAC_TYPE
FROM Health_Facility_Location
WHERE FACNAME LIKE '%ACUTE%'
GROUP BY FAC_TYPE_CODE
)

--COUNT OF ACUTE BEDS
SELECT 
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS_BY_FAC_TYPE
FROM Health_Facility_Location
WHERE FACNAME LIKE '%ACUTE%'

--SAVE AS VIEW
CREATE VIEW VW_ACUTE_BEDS AS
(
SELECT 
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS
FROM Health_Facility_Location
WHERE FACNAME LIKE '%ACUTE%'
)
--CAN BE CERTIFIED ACUTE BEDS
SELECT 
COUNT(CAPACITY) AS CAN_BE_CERTIFIED_ACUTE_BEDS
FROM Health_Facility_Location
WHERE FACNAME LIKE '%ACUTE%'
and CAN_BE_CERTIFIED_FAC_TYPE='Y';

--SAVE AS VIEW
CREATE VIEW VW_CAN_BE_CERTIFIED_ACUTE_BEDS AS
(
SELECT 
COUNT(CAPACITY) AS CAN_BE_CERTIFIED_ACUTE_BEDS
FROM Health_Facility_Location
WHERE FACNAME LIKE '%ACUTE%'
and CAN_BE_CERTIFIED_FAC_TYPE='Y'
)

--STATUS COUNT OF facilities
SELECT 
COUNT(licensed_certified) AS [LICENSED ONLY]
FROM Health_Facility_Location
WHERE LICENSED_CERTIFIED ='LICENSED ONLY'

SELECT 
COUNT(licensed_certified) AS [LICENSED AND CERTIFIED]
FROM Health_Facility_Location
WHERE LICENSED_CERTIFIED ='LICENSED AND CERTIFIED'

SELECT 
COUNT(licensed_certified) AS [NOT LICENSED/NOT CERTIFIED]
FROM Health_Facility_Location
WHERE LICENSED_CERTIFIED ='NOT LICENSED/NOT CERTIFIED'

SELECT 
COUNT(licensed_certified) AS [CERTIFIED ONLY]
FROM Health_Facility_Location
WHERE LICENSED_CERTIFIED ='CERTIFIED ONLY'

SELECT 
COUNT(licensed_certified) AS STATUS
FROM Health_Facility_Location

--ALTERNATIVELY USING PIVOT TO SHOW STATUS COUNT
SELECT *
FROM
(
SELECT LICENSED_CERTIFIED,
COUNT(LICENSED_CERTIFIED) AS STATUS
FROM Health_Facility_Location
GROUP BY LICENSED_CERTIFIED
) SOURCETABLE
	PIVOT (SUM([STATUS])
	FOR [LICENSED_CERTIFIED] IN 
	([CERTIFIED ONLY],
	[LICENSED ONLY],
	[LICENSED AND CERTIFIED],
	[NOT LICENSED/NOT CERTIFIED])
	) STATUSPIVOT

--SAVE AS VIEW
CREATE VIEW VW_STATUS_COUNT AS
(
SELECT *
FROM
(
SELECT LICENSED_CERTIFIED,
COUNT(LICENSED_CERTIFIED) AS STATUS
FROM Health_Facility_Location
GROUP BY LICENSED_CERTIFIED
) SOURCETABLE
	PIVOT (SUM([STATUS])
	FOR [LICENSED_CERTIFIED] IN 
	([CERTIFIED ONLY],
	[LICENSED ONLY],
	[LICENSED AND CERTIFIED],
	[NOT LICENSED/NOT CERTIFIED])
	) STATUSPIVOT
	)